### ISSUE TITLE
@faboslav You litte F**ker You made a shit of piece with your trash mod it’s f**King Bad this trash mod I will become back my money I hope you will in your next time a cow on a trash farm you sucker 

### ISSUE THREAD

**Issue by BabaIsBooey** [Faboslav/enhanced-buzzy-bees#7]
in other words, get your own textures. :)

**Comment by Faboslav** [comment]
I see that Alex has very toxic community, i was inspired by that mode, but i modeled and textured all things by my hand.

**Comment by PlummetStudios** [comment]
> I see that Alex has very toxic community, i was inspired by that mode, but i modeled and textured all things by my hand.

NO you didn't, you stole the code.
